name: Build & deploy Next.js app to Azure Web App

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]

  # Allow manual workflow trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🌱 Checkout to the branch
        uses: actions/checkout@v3

      - name: 🍏 Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: ⚙️ npm install and build
        run: |
          cd ./src
          npm install
          npm run build --if-present
          cd ..

      - name: 📂 Copy standalone into the root
        run: cp -R ./src/.next/standalone ./site-deploy

      - name: 📂 Copy static into the .next folder
        run: cp -R ./src/.next/static ./site-deploy/.next/static

      - name: 📂 Copy Public folder
        run: cp -R ./src/public ./site-deploy/public

      - name: 📦 Package Next application
        run: |
          cd ./site-deploy
          zip Nextjs-site.zip ./* .next -qr

      - name: 🔍 Diagnostics
        run: |
          ls ./src
          ls ./src/.next
          ls ./site-deploy

      - name: ⬆️ Publish Next Application artifact
        uses: actions/upload-artifact@v3
        with:
          name: Nextjs-site
          path: ./site-deploy/Nextjs-site.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: ⬇️ Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: Nextjs-site

      - name: 🗝️ Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set the build during deployment setting to false. This setting was added in the templates to all azd to work, but breaks deployment via webapps-deploy
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            rg=$(az webapp list --query "[?name=='${{ secrets.AZURE_APP_SERVICE_NAME }}'].resourceGroup" --output tsv)
            echo Setting SCM_DO_BUILD_DURING_DEPLOYMENT=false on app service ${{ secrets.AZURE_APP_SERVICE_NAME }}
            az webapp config appsettings set -n ${{ secrets.AZURE_APP_SERVICE_NAME }} -g $rg -o none \
              --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false \
              --settings OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }} \
              --settings AZURE_OPENAI_API_INSTANCE_NAME=${{ secrets.AZURE_OPENAI_API_INSTANCE_NAME }} \
              --settings AZURE_OPENAI_API_DEPLOYMENT_NAME=${{ secrets.AZURE_OPENAI_API_DEPLOYMENT_NAME }} \
              --settings AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }} \
              --settings AZURE_COSMOSDB_URI=${{ secrets.AZURE_COSMOSDB_URI }} \
              --settings AZURE_COSMOSDB_KEY=${{ secrets.AZURE_COSMOSDB_KEY }} \
              --settings AZURE_COSMOSDB_DB_NAME=${{ secrets.AZURE_COSMOSDB_DB_NAME }} \
              --settings AZURE_COSMOSDB_CONTAINER_NAME=${{ secrets.AZURE_COSMOSDB_CONTAINER_NAME }} \
              --settings ADMIN_EMAIL_ADDRESS=${{ secrets.ADMIN_EMAIL_ADDRESS }} \
              --settings AUTH_OKTA_ID=${{ secrets.AUTH_OKTA_ID }} \
              --settings AUTH_OKTA_SECRET=${{ secrets.AUTH_OKTA_SECRET }} \
              --settings AUTH_OKTA_ISSUER=${{ secrets.AUTH_OKTA_ISSUER }} \
              --settings NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
              --settings NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
              --settings NODE_ENV=production
            echo Setting --startup-file=\"node server.js\" on app service ${{ secrets.AZURE_APP_SERVICE_NAME }}
            az webapp config set --startup-file="node server.js" -n ${{ secrets.AZURE_APP_SERVICE_NAME }} -g $rg -o none
            sleep 10

      - name: 🚀 Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
          package: ${{ github.workspace }}/Nextjs-site.zip

      - name: 🧹 Cleanup
        run: rm ${{ github.workspace }}/Nextjs-site.zip
